# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AOO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AOO
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  target 'AOOTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AOO-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AOO-tvOS

  target 'AOO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
